# Generated by Django 3.0.3 on 2021-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_building_buildingtenant_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
